# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174ae406492ee9944c8eb5d5aaa8217f6a2c9cf071fb0d3dc2ab48c68835c759df330a3128a35a67375ef7706940f7f72f000cadcf80a38c9b0244286ce2d28b

test:
  secret_key_base: 6ef50b5d8ad50393dab4f689ee7a65734167497954979b726e378c891d4bfaf4927afe5114b96e6d8b2cf8f3911ea798b202d193e4c88e4366e0a4e3a09f094a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
